# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Email report
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Daily report
          body: |
            This is the daily report.
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          attachments: report